### ISSUE TITLE
Legacy API vs REST API

### ISSUE THREAD

**Issue by HelloTiago** [Receiptful/node-woocommerce#15]
I'd like to use the latest REST API but this only seems to work with the legacy API's, which are now deprecated. Changing the api path to `apiPath: '/wp-json/wc/v1'` throws 401 Unauthorised errors.

How would I proceed in updating this to the latest REST API?

**Comment by dlebech** [comment]
@HelloTiago Thank you for bringing this to our attention. I can confirm as well that it doesn't seem to work with the new API endpoint.

After some quick testing, it seems that I can fix this by removing `last_ampersand: false` from here: https://github.com/Receiptful/node-woocommerce/blob/master/lib/request.js#L26-L27

This, in turn, makes the old API return 401 errors so there probably needs to be some kind of `isLegacy` flag added in, either explicit via an option or implicit by checking the API version.

It's late in the day so I wouldn't call this a fix yet, but I think we're on the right track :-) Let me know if you are able to test this as well.

**Comment by HelloTiago** [comment]
@dlebech You're welcome!

I tried cloning this repo and basically "including" it manually on my existing project and using that instead of the NPM version. I'm guessing that's not how you properly test a package 🙈

**Comment by dlebech** [comment]
By the way, for the sake of full transparency, I should mention that our library is not the officially supported one: https://www.npmjs.com/package/woocommerce-api

I've fixed the issue in #16. If I get a go from my colleagues, I can publish it tomorrow :-)

**Comment by dlebech** [comment]
@HelloTiago If you get a chance to test the branch `support-new-api` as well, that would be great. Let me know what you think

**Comment by HelloTiago** [comment]
@dlebech Thanks, I'm actually having some (similar) issues with the officially supported library hah. https://github.com/woocommerce/wc-api-node/issues/43#issuecomment-256376525

I just tested the `support-new-api` branch, and I keep getting 401 errors, with and without SSL: `woocommerce_rest_cannot_view`, which is the same error I get with the official lib. Did you manage to get this working with the changes you made?

**Comment by dlebech** [comment]
@HelloTiago Yes, I was running a local WooCommerce installation and tested the updated lib with the following little script:
```
'use strict';

const WC = require('./lib/woocommerce');

const wc1 = new WC({
  url: 'http://woocommerce.dev',
  ssl: false,
  consumerKey: 'somekey',
  secret: 'somesecret',
});

const wc2 = new WC({
  url: 'http://woocommerce.dev',
  ssl: false,
  consumerKey: 'somekey',
  secret: 'somesecret',
  apiPath: '/wp-json/wc/v1'
});

wc1.get('/products').then(p => console.log(p.products.length)).catch(console.error);
wc2.get('/products').then(p => console.log(p.length)).catch(console.error);
```
The call for `wc2` failed before the changes I made on the `support-new-api` branch.

So it sounds like you might have an installation problem? Did you forward query string in your `try_files` for the nginx configuration (`try_files $uri $uri/ /index.php?$args;`) and enabled pretty urls in Wordpress? Those are the two main things that I can think of off the top of my head when it comes to config issues.

**Comment by HelloTiago** [comment]
@dlebech Strange... can't get it to work here.

My `try_files` config was slightly different. Modified that but still no luck.. Also testing on the same site deployed on a web host and it isn't working either 😞

**Comment by dlebech** [comment]
@HelloTiago I went ahead and merged the PR, published it as version 2.4.0. It should show up on npm soon.

**Comment by dlebech** [comment]
@HelloTiago I was able to get this working using both https and http on a remote installation and both new and legacy APIs. This is my full nginx config for the site (a few things redacted):
```
# WooCommerce
server {
    listen       80;
    listen       443 ssl;
    server_name  the.shopdomain.com;
    root /the/web/root;
    index index.php;

    ssl on;
    ssl_certificate /some/path/to/fullchain.pem;
    ssl_certificate_key /some/path/to/privkey.pem;

    try_files $uri $uri/ /index.php?$args;

    location ~ \.php$ {
        include        fastcgi_params;
        fastcgi_pass   unix:/var/run/php/php7.0-fpm.sock;
        fastcgi_intercept_errors on;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
```

**Comment by HelloTiago** [comment]
@dlebech Thanks for taking the time to reply! Sadly that didn't work either though :/ Tried on a fresh install with Nginx or Apache.

I guess I'll just go with the V3 API, no idea what else to try at this point.

**Comment by dlebech** [comment]
@HelloTiago I'm sorry to hear that :-(

Regarding whether it's a bug in WooCommerce, I can't answer that as I'm not familiar with the inner workings of it :-) The fix that I pushed this morning solved the issues with the new API for me both with and without oauth so I don't know why it doesn't work in your case. Perhaps check the system status page for WooCommerce to see if there's any red warnings. Perhaps a php library is missing or something. Other than that, I don't know what else to suggest unfortunately.

**Comment by HelloTiago** [comment]
@dlebech It turns out the issue was in part due to my server not parsing the auth headers correctly, and in part due to browser caching. Once I tried going through everything in incognito mode the requests started succeeding 😄 So yeah, heavy browser caching on HTTP requests was the answer!

Again, thank you for your help!

**Comment by dlebech** [comment]
@HelloTiago I'm happy it worked out for you and thank you for following up on this issue. Cheers :+1:
